### ISSUE TITLE
Remove replace state attribute

### ISSUE THREAD

**Issue by erxclau** [michigandaily/alt-text-tracker#31]
I'm finding this replace state attribute kind of frustrating. I keep sliding my trackpad to go back because that's typically how i navigate between pages. Instead of going back to the main page, it goes back to the page before visiting the website. Was this introduced for the paging for specific articles? If so, I think the replace state could be placed somewhere else.

https://github.com/michigandaily/alt-text-tracker/blob/cdc708f11d7c81875ddd83f531dbeaf53d0fdfee/src/app.html#L43

**Comment by yum25** [comment]
Yeah, I initially didn't want to produce a large amount of page history, but it's starting to become annoying for me as well
