### ISSUE TITLE
Fix cases with invalid number counts

### ISSUE THREAD

**Issue by erxclau** [michigandaily/alt-text-tracker#5]
I've run into a few cases where the numerator and denominator don't make sense.

<img width="392" alt="Screenshot 2024-03-13 at 4 41 36 PM" src="https://github.com/michigandaily/alt-text-tracker/assets/44459660/4d93e924-b231-4756-8ead-fc8152a1acf3">

The [article](https://www.michigandaily.com/uncategorized/alhamdulillah/) for this card _does_ have a featured image and a potentially broken image.

**Comment by yum25** [comment]
Closed with https://github.com/michigandaily/alt-text-tracker/pull/29
